"""Append-on-emit JSONL writer for detection export (DET-METRICS-04).

Per CONTEXT D-11 / D-12 and RESEARCH Pitfall 6 + Open Question 4:

- Writes to `<tempfile.gettempdir()>/argus_sessions/<session_id>/detections.jsonl`
  in append + line-buffered text mode (``open(..., "a", buffering=1)``) so
  that SIGKILL preserves every line that finished a ``\\n``-terminated write.
- Session id is a UUID4 generated by the caller (coordinator boot). This
  module never accepts path fragments or slashes — callers MUST pass an
  opaque identifier.
- ``rotate(new_session_id)`` closes the current file under a
  ``threading.Lock`` and opens a new session directory. Prior files are
  NOT deleted (they are debug artifacts per D-12).
- ``append`` and ``rotate`` share the same lock so a REST-handler-thread
  rotation cannot race a coordinator-thread write.

Security (T-6-02): session path uses a server-generated UUID4 composed with
``tempfile.gettempdir() / "argus_sessions" / session_id``. There is no
``Path.join`` of user data. Callers MUST NOT pass user-supplied strings as
``session_id``; do ``uuid.uuid4().hex`` and hand that through.

DoS (T-6-03): ``/tmp`` disk growth is accepted per CONTEXT D-12 — the
directory is debug-only and OS/user cleanup is out of scope for the writer.
"""
from __future__ import annotations

import json
import tempfile
import threading
from pathlib import Path
from typing import Any, TextIO

__all__ = ["DetectionExportWriter"]


class DetectionExportWriter:
    """Per-session JSONL writer with lock-protected rotation.

    The writer opens exactly one file at a time. ``append`` is the only
    write path and emits a single newline-terminated JSON object per call.
    ``rotate`` closes the current file and opens a new session directory
    atomically with respect to in-flight ``append`` calls (single
    ``threading.Lock`` guards both).

    Wire format (one line, no whitespace between tokens)::

        {"robot_id":"robot_0","backend_id":"yolov11",
         "capture_timestamp":12.345,
         "obb":{...OrientedBox3D.to_wire()...}}

    ``obb`` is produced exclusively by ``OrientedBox3D.to_wire()`` — the
    Phase 1 D-10 invariant that quaternion canonicalization has a single
    code path.

    Parameters
    ----------
    session_id:
        Opaque session identifier (expected: ``uuid.uuid4().hex``). The
        writer uses this as a subdirectory name verbatim; callers are
        responsible for sourcing it from a trusted generator.
    base_dir:
        Base directory under which ``argus_sessions/<session_id>/`` is
        created. Defaults to ``tempfile.gettempdir()`` — OS-portable and
        user-local. Tests pass a ``tmp_path`` fixture to keep hermetic.
    """

    def __init__(self, session_id: str, base_dir: Path | None = None) -> None:
        self._base_dir: Path = Path(base_dir) if base_dir is not None else Path(tempfile.gettempdir())
        self._lock = threading.Lock()
        self._fp: TextIO | None = None
        self._file_path: Path | None = None
        self._session_id: str = str(session_id)
        # Open initial session file before returning so callers can rely on
        # `file_path` / `session_id` immediately.
        self._open_for_session(self._session_id)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def _open_for_session(self, session_id: str) -> None:
        """Open a fresh append handle for `session_id`.

        MUST be called with `self._lock` held (or from `__init__` prior to
        any external reference leaking). Creates the session directory if
        needed; uses text-mode line-buffered append so a `\\n`-terminated
        write flushes before returning (RESEARCH Pitfall 6).
        """
        session_dir = self._base_dir / "argus_sessions" / session_id
        session_dir.mkdir(parents=True, exist_ok=True)
        path = session_dir / "detections.jsonl"
        # buffering=1 -> line-buffered for text mode; flushes on '\n'.
        # encoding explicit to avoid platform-default surprises.
        self._fp = open(path, "a", buffering=1, encoding="utf-8")
        self._file_path = path
        self._session_id = session_id

    @property
    def session_id(self) -> str:
        return self._session_id

    @property
    def file_path(self) -> Path:
        assert self._file_path is not None, "writer has no file path (never opened?)"
        return self._file_path

    # ------------------------------------------------------------------
    # Writes
    # ------------------------------------------------------------------
    def append(
        self,
        obb: Any,  # OrientedBox3D (duck-typed on .to_wire())
        robot_id: str,
        backend_id: str,
        capture_timestamp: float,
    ) -> None:
        """Append one JSONL record for `obb` with envelope metadata.

        Silently no-ops after ``close()`` so a late-arriving pump does not
        crash on shutdown. Callers that care about write durability should
        check ``writer.file_path.stat().st_size`` after a known-last flush.
        """
        record = {
            "robot_id": str(robot_id),
            "backend_id": str(backend_id),
            "capture_timestamp": float(capture_timestamp),
            "obb": obb.to_wire(),  # Phase 1 D-10: sole quaternion path
        }
        # separators=(',', ':') -> compact; no trailing spaces; stable.
        line = json.dumps(record, separators=(",", ":")) + "\n"
        with self._lock:
            if self._fp is None:
                return
            self._fp.write(line)

    def rotate(self, new_session_id: str) -> None:
        """Close current file and open a new session file atomically.

        Safe to call from a different thread than `append`. Old session file
        is NOT deleted (D-12 — prior session files are debug artifacts).
        """
        with self._lock:
            if self._fp is not None:
                self._fp.close()
                self._fp = None
            self._open_for_session(str(new_session_id))

    def close(self) -> None:
        """Close the open file handle. Idempotent."""
        with self._lock:
            if self._fp is not None:
                self._fp.close()
                self._fp = None
